before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libssl-dev libpcre3-dev wget unzip libavcodec-dev libavfilter-dev
language: c
compiler:
    - clang
    - gcc
script: ./travis_build.sh

